### ISSUE TITLE
requirements.txt  please?

### ISSUE THREAD

**Issue by shanff** [ytang07/click-tutorial#1]
Great Blog post - however one issue I see is that it's not running with later versions of click.  I assume this is the case, anyway, and I'm on an Arch Linux distribution.  Can you provide a requirements.txt for this?  

This looks like a fantastic tutorial to follow, I just ran into some weird issues with get_keys.  It's complaining that it's returning a list instance but was expecting a string?  I mean, I don't doubt the code is proper, but I have click.__version__ returning '7.1.2', 

I'm guessing something's changed somewhere.

**Comment by ytang07** [comment]
I can get a requirements.txt up in a bit, what version of Python are you using?

I have been unable to reproduce this error. It should be returning a list and expecting a list so I am equally confused.

**Comment by shanff** [comment]
[20:34:48]  yay -Qa|grep python|egrep -e "^python\s" -e click
python 3.9.7-1
python-click 8.0.1-1
python-click-completion 0.5.2-5

**Comment by ytang07** [comment]
![image](https://user-images.githubusercontent.com/17556662/136553088-97afc69e-c34e-4905-8580-b6482b58dff6.png)
is this what your error looks like?

**Comment by shanff** [comment]
That's exactly the error I'm getting.

**Comment by ytang07** [comment]
Okay, this is the intended behavior, what you'll want to do is send it either a ".json" like the one provided or a ".mp3" to transcribe. If you look at the "main" function, you'll see that it branches off to do two different CLIs depending on the input, sorry for the confusion, I'll update the README
